# Generated by Django 4.1.7 on 2023-03-20 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("handleMovies", "0002_movieslist_poster_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="movieslist",
            name="is_fixed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="movieslist",
            name="poster_url",
            field=models.CharField(
                default="https://skydomepictures.com/wp-content/uploads/2018/08/movie-poster-coming-soon-2.png",
                max_length=1000,
            ),
        ),
    ]
